### ISSUE TITLE
Traceback error on Arch Linux

### ISSUE THREAD

**Issue by skippa** [PythonTurtle/PythonTurtle#161]
Installed as per instructions, when I run PythonTurtle I get this:
`Traceback (most recent call last):
  File "/home/noah/.local/bin/PythonTurtle", line 8, in <module>
    sys.exit(application.run())
  File "/home/noah/.local/lib/python3.10/site-packages/pythonturtle/application.py", line 223, in run
    ApplicationWindow(None, -1, pythonturtle.name, size=(600, 600))
  File "/home/noah/.local/lib/python3.10/site-packages/pythonturtle/application.py", line 59, in __init__
    shelltoprocess.Shell(self.bottom_sizer_panel,
  File "/home/noah/.local/lib/python3.10/site-packages/pythonturtle/shelltoprocess/shell.py", line 41, in __init__
    ForkedShell.__init__(self, parent, *args,
  File "/home/noah/.local/lib/python3.10/site-packages/pythonturtle/shelltoprocess/forkedpyshell.py", line 318, in __init__
    self.Bind(wx.EVT_MENU,
  File "/usr/lib/python3.10/site-packages/wx/core.py", line 1406, in _EvtHandler_Bind
    event.Bind(self, id, id2, handler)
  File "/usr/lib/python3.10/site-packages/wx/core.py", line 1477, in Bind
    target.Connect(id1, id2, et, function)
TypeError: EvtHandler.Connect(): argument 1 has unexpected type 'WindowIDRef'
`
wxPython version is 4.0.7.post2

Any ideas?

**Comment by skippa** [comment]
Is it a version mismatch problem here?

**Comment by cool-RR** [comment]
Hmm, I see that the answer I sent by email was ignored by GitHub for some reason:

I don't know, sorry. It's possible it's because the wxPython version is too high, you could try using it in a virtualenv with an old version. This is a project from 2009 that isn't very maintained.

**Comment by cool-RR** [comment]
I don't know, sorry. It's possible it's because the wxPython version is too
high, you could try using it in a virtualenv with an old version. This is a
project from 2009 that isn't very maintained.

**Comment by bittner** [comment]
According to [our README](https://github.com/PythonTurtle/PythonTurtle#compatibility) the supported wxPython version is 4.0.1.

If you're willing to find out what changed in their API since that version we could add some conditional code the make it work for both that and your newer version of wxPython.

A pull request to fix the problem would be awesome!

**Comment by ShaunRoselt** [comment]
I also get some kind of traceback error:

```
📦[deck@Python ~]$ PythonTurtle
/home/deck/.local/lib/python3.13/site-packages/pythonturtle/misc/helpers.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Gtk-Message: 07:50:19.210: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:50:19.232: Failed to load module "colorreload-gtk-module"
Gtk-Message: 07:50:19.232: Failed to load module "window-decorations-gtk-module"
Traceback (most recent call last):
  File "/home/deck/.local/lib/python3.13/site-packages/pythonturtle/turtlewidget.py", line 64, in on_paint
    dc.DrawBitmap(self.bitmap, *top_left_corner)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DC.DrawBitmap(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/home/deck/.local/lib/python3.13/site-packages/pythonturtle/turtlewidget.py", line 64, in on_paint
    dc.DrawBitmap(self.bitmap, *top_left_corner)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DC.DrawBitmap(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Segmentation fault         (core dumped) PythonTurtle
```

**Comment by cool-RR** [comment]
Hi Shaun. I'm sorry, PythonTurtle has been bottom priority for me for a long time. It's unlikely anyone will help. If you have time I suggest you get Claude Code to take a stab at it.
